### ISSUE TITLE
Problem in Step 3 :( 

### ISSUE THREAD

**Issue by Ashraf95Nagy** [everydeveloper/intermediate-python#1]
I'm facing a problem in the course " Intermediate Python" at step 3 which is conditions,
I've pushed the code file without any responding from your bot, and I'm still waiting :D
And Please Check the Attached file if there is any mistake in coding ( might be )

**Comment by brianamarie** [comment]
Hello @adamd 👋 This has been coming up for multiple users. Would you have a chance to take a look? Thanks!

**Comment by adamd** [comment]
Ugh, sorry about that. We'll take a look!

**Comment by adamd** [comment]
@Ashraf95Nagy Thanks for bringing this to our attention! It's fixed, but only in the latest versions of the course. You'll need to delete the repo and start at the beginning (everything is the same up to that point, so you can breeze through with pushes and comments).

Once you delete your repo, you can [enroll again here](https://lab.github.com/everydeveloper/intermediate-python).
